name: Python Package using Conda

on: [push]  # Potential issue: Improper list or key format

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies, Test, and Cleanup Environment
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        conda install pytest
        pytest
        conda env remove -n crop-recommendation-env

conda env create -f environment.yml
conda update -n base -c defaults conda
conda install mamba -n base -c conda-forge
mamba env create -f environment.yml
conda create -n crop-recommendation-env python=3.8
conda activate crop-recommendation-env
# Install packages one by one
