name: Python Package using Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: crop-recommendation-env
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false

      - name: Remove Existing Environment (if exists)
        run: |
          conda env remove -n crop-recommendation-env || true

      - name: Create Conda Environment
        run: |
          conda env create -f environment.yml

      - name: Install Linting and Testing Tools
        run: |
          conda install flake8 pytest -y

      - name: Lint with Flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with Pytest
        run: |
          pytest

